### ISSUE TITLE
Invalid audience

### ISSUE THREAD

**Issue by kevinrenskers** [hwjeremy/siwa-python#1]
Thanks for creating this library, it really helps to streamline the verification and decoding of Apple's id tokens. However, I'm running into the problem where `is_validly_signed` always returns false, and turns out the error is `Invalid audience`. Indeed this seems to be hardcoded to `blinkybeach.Makara`?

This this needs to be set to my own client id, this needs to be configurable.

**Comment by hwjeremy** [comment]
Thanks for catching this mate! I'll check out your pull in the morning! 😊

**Comment by hwjeremy** [comment]
🎉 Issue resolved: https://github.com/hwjeremy/siwa-python/releases/tag/0.0.6
