### ISSUE TITLE
Make `audience` optional in `is_validly_signed`?

### ISSUE THREAD

**Issue by kevinrenskers** [hwjeremy/siwa-python#3]
Would it make sense to have the `is_validly_signed` function work if you don't give the `audience` parameter? That it would simply ignore it? The use case is that if I have a mobile app and a web app both using Sign In with Apple, that their audiences differ. So now I have to know the source of the request, to be able to pass in the correct audience. I just wonder if ignoring the audience would really hurt security, as I see many other libraries that don't validate the audience at all.

**Comment by hwjeremy** [comment]
@kevinrenskers I'm not entirely sure what the security consequences would be of failing to verify the audience. I'm not sure PyJWT, the library that performs JWT verification for siwa-python, supports verification without audience where the underlying token has been signed with an audience. I'm not super familiar with the JWT specification but a quick glance makes me thing audience verification is essential if the service provider (in this case, Apple) is specifying it as part of the token.

Given all these unknowns, I don't think it makes sense to try to optionalise the audience. In your case, where you have a mobile app and a web app, I would suggest that you could use [AppleJS](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js) for the web app.

If you're not worried about the consequences of a client masquerading as one or another audience (I'm not sure what those consequences would be), you could also simply pass the audience as part of your own request. Perhaps in the request body, or even as a header.

**Comment by kevinrenskers** [comment]
I've looked at some Swift and JavaScript libraries, and they had it all optional, so yeah I am not sure about the security implications either but they seemed to think it wasn't a problem. It's not a big deal, I am passing along the source of the request (web / app) so I can give the correct audience, but it feels a bit clunky compared to the other libraries where it's just optional. 

But like I said, not a big deal, feel free to close this issue.
