### ISSUE TITLE
crash with pyJWT 2.2.0

### ISSUE THREAD

**Issue by mjamroz** [hwjeremy/siwa-python#4]
version 2.2.0 of https://pyjwt.readthedocs.io/en/2.2.0/changelog.html#dropped-deprecated-verify-param-in-jwt-decode
doesn't user `verify` parameter here:
https://github.com/hwjeremy/siwa-python/blob/6b8a36c7c68958962131ff278b9aac2a1566e44a/siwa/library/token/token.py#L57 

could we ask to update your code or define pyjwt highest compatible  version?

**Comment by hwjeremy** [comment]
@mjamroz thanks for pointing this out Michal, much appreciated. I've deployed a new version with resolves the problem: https://github.com/hwjeremy/siwa-python/releases/tag/0.0.7.

Closing this issue as resolved, feel free to re-open it if you find the update does not solve the problem for you.
